 CREATE TABLE `p_releases` (
   `artist` varchar(255) NOT NULL,
   `title` varchar(255) NOT NULL,
   `country` varchar(41) DEFAULT NULL,
   `genre` varchar(22) DEFAULT NULL,
   `style` varchar(27) DEFAULT NULL,
   `release_date` date NOT NULL,
   `discogs_url` varchar(501) DEFAULT NULL,
   `title_prefix` char(2) GENERATED ALWAYS AS (left(`title`,2)) STORED NOT NULL,
   PRIMARY KEY (`title`,`artist`,`release_date`,`title_prefix`)
 )
 PARTITION BY LIST  COLUMNS(title_prefix)
 (PARTITION p_0 VALUES IN ('00','01','02','03','04','05','06','07','08','09'),
    PARTITION p_1 VALUES IN ('10','11','12','13','14','15','16','17','18','19'),
    PARTITION p_2 VALUES IN ('20','21','22','23','24','25','26','27','28','29'),
    PARTITION p_3 VALUES IN ('30','31','32','33','34','35','36','37','38','39'),
    PARTITION p_4 VALUES IN ('40','41','42','43','44','45','46','47','48','49'),
    PARTITION p_5 VALUES IN ('50','51','52','53','54','55','56','57','58','59'),
    PARTITION p_6 VALUES IN ('60','61','62','63','64','65','66','67','68','69'),
    PARTITION p_7 VALUES IN ('70','71','72','73','74','75','76','77','78','79'),
    PARTITION p_8 VALUES IN ('80','81','82','83','84','85','86','87','88','89'),
    PARTITION p_9 VALUES IN ('90','91','92','93','94','95','96','97','98','99'),
    PARTITION p_A VALUES IN ('A ','AA','AB','AC','AD','AE','AF','AG','AH','AI','AJ','AK','AL','AM','AN','AO','AP','AQ','AR','AS','AT','AU','AV','AW','AX','AY','AZ'),
    PARTITION p_B VALUES IN ('B ','BA','BB','BC','BD','BE','BF','BG','BH','BI','BJ','BK','BL','BM','BN','BO','BP','BQ','BR','BS','BT','BU','BV','BW','BX','BY','BZ'),
    PARTITION p_C VALUES IN ('C ','CA','CB','CC','CD','CE','CF','CG','CH','CI','CJ','CK','CL','CM','CN','CO','CP','CQ','CR','CS','CT','CU','CV','CW','CX','CY','CZ'),
    PARTITION p_D VALUES IN ('D ','DA','DB','DC','DD','DE','DF','DG','DH','DI','DJ','DK','DL','DM','DN','DO','DP','DQ','DR','DS','DT','DU','DV','DW','DX','DY','DZ'),
    PARTITION p_E VALUES IN ('E ','EA','EB','EC','ED','EE','EF','EG','EH','EI','EJ','EK','EL','EM','EN','EO','EP','EQ','ER','ES','ET','EU','EV','EW','EX','EY','EZ'),
    PARTITION p_F VALUES IN ('F ','FA','FB','FC','FD','FE','FF','FG','FH','FI','FJ','FK','FL','FM','FN','FO','FP','FQ','FR','FS','FT','FU','FV','FW','FX','FY','FZ'),
    PARTITION p_G VALUES IN ('G ','GA','GB','GC','GD','GE','GF','GG','GH','GI','GJ','GK','GL','GM','GN','GO','GP','GQ','GR','GS','GT','GU','GV','GW','GX','GY','GZ'),
    PARTITION p_H VALUES IN ('H ','HA','HB','HC','HD','HE','HF','HG','HH','HI','HJ','HK','HL','HM','HN','HO','HP','HQ','HR','HS','HT','HU','HV','HW','HX','HY','HZ'),
    PARTITION p_I VALUES IN ('I ','IA','IB','IC','ID','IE','IF','IG','IH','II','IJ','IK','IL','IM','IN','IO','IP','IQ','IR','IS','IT','IU','IV','IW','IX','IY','IZ'),
    PARTITION p_J VALUES IN ('J ','JA','JB','JC','JD','JE','JF','JG','JH','JI','JJ','JK','JL','JM','JN','JO','JP','JQ','JR','JS','JT','JU','JV','JW','JX','JY','JZ'),
    PARTITION p_K VALUES IN ('K ','KA','KB','KC','KD','KE','KF','KG','KH','KI','KJ','KK','KL','KM','KN','KO','KP','KQ','KR','KS','KT','KU','KV','KW','KX','KY','KZ'),
    PARTITION p_L VALUES IN ('L ','LA','LB','LC','LD','LE','LF','LG','LH','LI','LJ','LK','LL','LM','LN','LO','LP','LQ','LR','LS','LT','LU','LV','LW','LX','LY','LZ'),
    PARTITION p_M VALUES IN ('M ','MA','MB','MC','MD','ME','MF','MG','MH','MI','MJ','MK','ML','MM','MN','MO','MP','MQ','MR','MS','MT','MU','MV','MW','MX','MY','MZ'),
    PARTITION p_N VALUES IN ('N ','NA','NB','NC','ND','NE','NF','NG','NH','NI','NJ','NK','NL','NM','NN','NO','NP','NQ','NR','NS','NT','NU','NV','NW','NX','NY','NZ'),
    PARTITION p_O VALUES IN ('O ','OA','OB','OC','OD','OE','OF','OG','OH','OI','OJ','OK','OL','OM','ON','OO','OP','OQ','OR','OS','OT','OU','OV','OW','OX','OY','OZ'),
    PARTITION p_P VALUES IN ('P ','PA','PB','PC','PD','PE','PF','PG','PH','PI','PJ','PK','PL','PM','PN','PO','PP','PQ','PR','PS','PT','PU','PV','PW','PX','PY','PZ'),
    PARTITION p_Q VALUES IN ('Q ','QA','QB','QC','QD','QE','QF','QG','QH','QI','QJ','QK','QL','QM','QN','QO','QP','QQ','QR','QS','QT','QU','QV','QW','QX','QY','QZ'),
    PARTITION p_R VALUES IN ('R ','RA','RB','RC','RD','RE','RF','RG','RH','RI','RJ','RK','RL','RM','RN','RO','RP','RQ','RR','RS','RT','RU','RV','RW','RX','RY','RZ'),
    PARTITION p_S VALUES IN ('S ','SA','SB','SC','SD','SE','SF','SG','SH','SI','SJ','SK','SL','SM','SN','SO','SP','SQ','SR','SS','ST','SU','SV','SW','SX','SY','SZ'),
    PARTITION p_T VALUES IN ('T ','TA','TB','TC','TD','TE','TF','TG','TH','TI','TJ','TK','TL','TM','TN','TO','TP','TQ','TR','TS','TT','TU','TV','TW','TX','TY','TZ'),
    PARTITION p_U VALUES IN ('U ','UA','UB','UC','UD','UE','UF','UG','UH','UI','UJ','UK','UL','UM','UN','UO','UP','UQ','UR','US','UT','UU','UV','UW','UX','UY','UZ'),
    PARTITION p_V VALUES IN ('V ','VA','VB','VC','VD','VE','VF','VG','VH','VI','VJ','VK','VL','VM','VN','VO','VP','VQ','VR','VS','VT','VU','VV','VW','VX','VY','VZ'),
    PARTITION p_W VALUES IN ('W ','WA','WB','WC','WD','WE','WF','WG','WH','WI','WJ','WK','WL','WM','WN','WO','WP','WQ','WR','WS','WT','WU','WV','WW','WX','WY','WZ'),
    PARTITION p_X VALUES IN ('X ','XA','XB','XC','XD','XE','XF','XG','XH','XI','XJ','XK','XL','XM','XN','XO','XP','XQ','XR','XS','XT','XU','XV','XW','XX','XY','XZ'),
    PARTITION p_Y VALUES IN ('Y ','YA','YB','YC','YD','YE','YF','YG','YH','YI','YJ','YK','YL','YM','YN','YO','YP','YQ','YR','YS','YT','YU','YV','YW','YX','YY','YZ'),
    PARTITION p_Z VALUES IN ('Z ','ZA','ZB','ZC','ZD','ZE','ZF','ZG','ZH','ZI','ZJ','ZK','ZL','ZM','ZN','ZO','ZP','ZQ','ZR','ZS','ZT','ZU','ZV','ZW','ZX','ZY','ZZ'),
    PARTITION p_catch_all VALUES IN ('??'));